### 作業目的: 更加熟習pytorch的tensor操作

pytorch中有提供很多的API，讓使用者針對tensor進行各式各樣的操作，本次的作業希望讀者由pytorch的[官方網站](https://pytorch.org/docs/stable/torch.html)中選定四個針對tensor操作的API，對他的使用方法進行範例操作演練。

### 選定的API 函數

**請寫下選定的API functions**

ex:
* torch.from_array() / tensor.numpy()
* torch.unsqueeze() / torch.squeeze()
* tensor.transpose() / tensor.permute()
* torch.reshape() / tensor.view()

In [1]:
# Import torch and other required modules
import torch
import numpy as np

### 範例:
### Function 1 - torch.from_array() / tensor.numpy()

In [2]:
# Example 1 - 將torch tensor與numpy ndarray互相轉換
a = np.random.rand(1,2,3,3)
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, float64
b: <class 'torch.Tensor'>, torch.float64
c: <class 'torch.Tensor'>, torch.float64
d: <class 'numpy.ndarray'>, float64


In [3]:
# Example 2 - 經過轉換後，torch tensor與numpy array依然有相近的資料型態
a = np.random.randint(low=0, high=10, size=(2,2))
print(f'a: {type(a)}, {a.dtype}')
b = torch.from_numpy(a)
print(f'b: {type(b)}, {b.dtype}')
c = torch.tensor(a)
print(f'c: {type(c)}, {c.dtype}')
d = c.numpy()
print(f'd: {type(d)}, {d.dtype}')

a: <class 'numpy.ndarray'>, int64
b: <class 'torch.Tensor'>, torch.int64
c: <class 'torch.Tensor'>, torch.int64
d: <class 'numpy.ndarray'>, int64


### Function 1 - torch.cat(tensors, dim=0) / torch.stack(tensors, dim=0)

In [4]:
# torch.cat(tensors, dim=0)
# Example 1 - 合併Tensor，但合併的Tensor必須為相同形狀(除了合併的那個dimension)或是empty。
### your code ###
a = torch.randn(1,2)
print(f'Original tensor:\n {a}')
print(f'◆Shape of original tensor1: {a.shape}')
b = torch.cat((a, a, a), 0)
print(f'Concat dim->0:\n {b}')
print(f'◆Shape of tensor after cat() dim=0: {b.shape}')
c = torch.cat((a, a, a), 1)
print(f'Concat dim->1:\n {c}')
print(f'◆Shape of tensor after cat() dim=0: {c.shape}')

Original tensor:
 tensor([[0.3542, 0.4953]])
◆Shape of original tensor1: torch.Size([1, 2])
Concat dim->0:
 tensor([[0.3542, 0.4953],
        [0.3542, 0.4953],
        [0.3542, 0.4953]])
◆Shape of tensor after cat() dim=0: torch.Size([3, 2])
Concat dim->1:
 tensor([[0.3542, 0.4953, 0.3542, 0.4953, 0.3542, 0.4953]])
◆Shape of tensor after cat() dim=0: torch.Size([1, 6])


In [5]:
# 承上 => 例如: shape(1,3,5)和shpae(2,3,5)的2個Tensor可以合併dimension0 但不能合併dimension1
a = torch.randn(1,3,5)
print(f'Original tensor1:\n {a}')
print(f'◆Shape of original tensor1: {a.shape}')
b = torch.randn(2,3,5)
print(f'Original tensor2:\n {b}')
print(f'◆Shape of original tensor2: {b.shape}')
c = torch.cat((a, b), 0)
print(f'Concat dim->0:\n {c}')
print(f'◆Shape of tensor after cat() dim=0: {c.shape}')
try: d = torch.cat((a, b), 1)
except Exception as e: print(f'Concat dim ->1\n Error message: {e}')

Original tensor1:
 tensor([[[ 0.5765,  0.3781,  0.7032,  0.3400,  1.0599],
         [-1.4289, -0.7743,  0.8325,  0.8499, -0.7492],
         [-0.1380, -0.2362,  1.8566, -0.1963,  0.4311]]])
◆Shape of original tensor1: torch.Size([1, 3, 5])
Original tensor2:
 tensor([[[-0.7602, -0.3037,  0.1338, -0.1680,  1.8010],
         [-1.7394,  0.7480, -2.9513,  0.9913, -0.6229],
         [ 0.0454, -0.3075, -1.6401,  0.6066, -1.0998]],

        [[ 0.6775, -0.8165, -1.0642,  0.8013,  0.8673],
         [-0.2965,  0.2279,  1.3807, -1.8515, -0.9649],
         [-0.4719, -0.1443,  1.4199,  0.7546, -2.3395]]])
◆Shape of original tensor2: torch.Size([2, 3, 5])
Concat dim->0:
 tensor([[[ 0.5765,  0.3781,  0.7032,  0.3400,  1.0599],
         [-1.4289, -0.7743,  0.8325,  0.8499, -0.7492],
         [-0.1380, -0.2362,  1.8566, -0.1963,  0.4311]],

        [[-0.7602, -0.3037,  0.1338, -0.1680,  1.8010],
         [-1.7394,  0.7480, -2.9513,  0.9913, -0.6229],
         [ 0.0454, -0.3075, -1.6401,  0.6066, -1.0998]

In [6]:
# torch.stack(tensors, dim=0)
# Example 2 - 產生一個維度(dimention)來合併Tensor => (增加新的維度進行堆疊)
# 新生成的Tensor的維度會是原本的Tensor的維度+1
# 所有要stack的Tesnsor都必須是相同形狀
# parameter-dim 指定生成的維度位置 (設定parameter-dim時，值不能超過新Tensor維度-1(index))
### your code ###
a = torch.randn(2,5)
b = torch.randn(2,5)
print(f'◆Shape of original tensor1&2: {a.shape}')
c = torch.stack((a,b,a),0)
print(f'◆Shape of tensor after stack() dim=0: {c.shape}')
c1 = torch.stack((a,b,a),1)
print(f'◆Shape of tensor after stack() dim=0: {c1.shape}')
c2 = torch.stack((a,b,a),2)
print(f'◆Shape of tensor after stack() dim=0: {c2.shape}')
try: torch.stack((a,b,a),3)
except Exception as e: print(e)

◆Shape of original tensor1&2: torch.Size([2, 5])
◆Shape of tensor after stack() dim=0: torch.Size([3, 2, 5])
◆Shape of tensor after stack() dim=0: torch.Size([2, 3, 5])
◆Shape of tensor after stack() dim=0: torch.Size([2, 5, 3])
Dimension out of range (expected to be in range of [-3, 2], but got 3)


### Function 2 - torch.chunk(input, chunks, dim=0) / torch.split(tensor, split_size_or_sections, dim=0)

In [7]:
# torch.chunk(input, chunks, dim=0) 
# Example 1 - 將Tensor分成數個Tensor(可指定分割大小、維度)，返回Tuple
# parameter-chunks 為一個整數，指定要將Tensor分成幾等份(會平等切分，但形狀不符合時chunk_size會不一樣)
### your code ###
a = torch.randn(5,2)
print(f'Original tensor:\n {a}')
print(f'◆Shape of original tensor: {a.shape}')
b = torch.chunk(a, 2)
print(f'Original tensor was cut into {len(b)} chunks')
print(f'◆Shape of the first tensor in the tuple(after splited): {b[0].shape}')
print(f'◆Shape of the last tensor in the tuple(after splited): {b[-1].shape}')

Original tensor:
 tensor([[-0.6664,  0.1594],
        [ 0.7987,  0.1172],
        [-1.4232,  0.6353],
        [-0.3045,  1.1243],
        [-1.4253,  0.4967]])
◆Shape of original tensor: torch.Size([5, 2])
Original tensor was cut into 2 chunks
◆Shape of the first tensor in the tuple(after splited): torch.Size([3, 2])
◆Shape of the last tensor in the tuple(after splited): torch.Size([2, 2])


In [8]:
# torch.split(tensor, split_size_or_sections, dim=0)
# Example 2 - 將Tensor分成數個Tensor(可指定分割大小、維度)，返回Tuple
# split_size_or_sections (int) or (list(int)) – 可以為一個整數來指定chunk的大小(會平等切分，但形狀不符合時最後一個chunk_size會不一樣)，也可以是一個整數列表指定分割的方式 
### your code ###
a = torch.randn(5,2)
print(f'Original tensor:\n {a}')
print(f'◆Shape of original tensor: {a.shape}')
b = torch.split(a, 2)
print(f'Original tensor was cut into {len(b)} chunks')
print(f'◆Shape of the first tensor in the tuple(after splited): {b[0].shape}')
print(f'◆Shape of the last tensor in the tuple(after splited): {b[-1].shape}')

Original tensor:
 tensor([[-0.5109, -0.8908],
        [-1.8915,  0.8386],
        [-0.3213,  0.5473],
        [-0.3586,  1.6448],
        [-0.1579, -0.5278]])
◆Shape of original tensor: torch.Size([5, 2])
Original tensor was cut into 3 chunks
◆Shape of the first tensor in the tuple(after splited): torch.Size([2, 2])
◆Shape of the last tensor in the tuple(after splited): torch.Size([1, 2])


### Function 3 - torch.vstack(tensors) / torch.hstack(tensors) 

In [9]:
# torch.vstack(tensors)
# Example 1 - 將Tensors垂直(row wise)堆疊
# column_size需相同
### your code ###
a = torch.randn(2,3)
print(f'Original tensor1:\n {a}')
b = torch.randn(4,3)
print(f'Original tensor1:\n {b}')
c = torch.vstack((a,b))
print(f'New tensor after vstack:\n {c}')
print(f'◆Shape of the new tensor: {c.shape}')

Original tensor1:
 tensor([[ 0.3618, -1.2087,  1.7439],
        [ 0.4061, -1.5153,  0.9452]])
Original tensor1:
 tensor([[-0.0776,  1.3922, -0.5062],
        [ 0.4406, -0.3946,  0.5017],
        [-1.4538, -0.1910,  0.7054],
        [-0.7925, -0.6989,  1.7084]])
New tensor after vstack:
 tensor([[ 0.3618, -1.2087,  1.7439],
        [ 0.4061, -1.5153,  0.9452],
        [-0.0776,  1.3922, -0.5062],
        [ 0.4406, -0.3946,  0.5017],
        [-1.4538, -0.1910,  0.7054],
        [-0.7925, -0.6989,  1.7084]])
◆Shape of the new tensor: torch.Size([6, 3])


In [10]:
# torch.hstack(tensors)
# Example 1 - 將Tensors水平(column wise)堆疊
# row_size需相同
### your code ###
a = torch.randn(4,1)
print(f'Original tensor1:\n {a}')
b = torch.randn(4,3)
print(f'Original tensor1:\n {b}')
c = torch.hstack((a,b))
print(f'New tensor after vstack:\n {c}')
print(f'◆Shape of the new tensor: {c.shape}')

Original tensor1:
 tensor([[-0.0700],
        [ 1.5725],
        [-0.4432],
        [-0.3291]])
Original tensor1:
 tensor([[-0.3082,  0.7533, -0.0889],
        [ 0.2970, -1.8399, -1.0290],
        [ 0.4488, -0.6088,  0.4160],
        [-2.4889,  0.6922, -0.0626]])
New tensor after vstack:
 tensor([[-0.0700, -0.3082,  0.7533, -0.0889],
        [ 1.5725,  0.2970, -1.8399, -1.0290],
        [-0.4432,  0.4488, -0.6088,  0.4160],
        [-0.3291, -2.4889,  0.6922, -0.0626]])
◆Shape of the new tensor: torch.Size([4, 4])


### Function 4 - torch.full(size, fill_value) / torch.where(condition, x, y)



In [11]:
# torch.full(size, fill_value)
# Example 1 - 給定size和fill_value產生一個全部值為fill_value的Tensor
### your code ###
a = torch.full((2, 3), 3.141592)
print(f'◆tensor:\n {a}')


◆tensor:
 tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])


In [12]:
# torch.where(condition, x, y)
# Example 2 - 給定一個條件&1~2個Tensors，返回一個根據條件產生的新Tensor。
# condition(BoolTensor) -> 給定一個條件，若True返回x，若False返回y
# x -> (Tensor or Scalar) 可為數值或Tensor，若不滿足condition時返回scalar value或對應位置的Tensor value
# y -> (Tensor or Scalar) 可為數值或Tensor，若不滿足condition時返回scalar value或對應位置的Tensor value
### your code ###
x = torch.randn(2, 2,dtype=torch.double)
y = torch.randn(2, 2,dtype=torch.double)
print(f'Original tensor1:\n {x}')
print(f'Original tensor2:\n {y}')
a = torch.where(x > 0, x, 0.) # tensor1:大於0的部分維持，小於0的部分則為0
b = torch.where(x > 0, x, y) #. tensor2:大於0的部分維持，小於0的部分則為y
c = torch.where(x > 0, 1., y) # tensor3:大於0的部分為1，小於0的部分則為y
print(f'New tensor1:\n {a}')
print(f'New tensor2:\n {b}')
print(f'New tensor3:\n {c}')

Original tensor1:
 tensor([[ 0.4317,  1.3663],
        [ 1.4299, -0.5986]], dtype=torch.float64)
Original tensor2:
 tensor([[-1.8131,  0.6613],
        [-0.4872,  0.0139]], dtype=torch.float64)
New tensor1:
 tensor([[0.4317, 1.3663],
        [1.4299, 0.0000]], dtype=torch.float64)
New tensor2:
 tensor([[0.4317, 1.3663],
        [1.4299, 0.0139]], dtype=torch.float64)
New tensor3:
 tensor([[1.0000, 1.0000],
        [1.0000, 0.0139]], dtype=torch.float64)
